"""Curated question bank: seeding and instant exam assembly.

Mock tests must start immediately, so questions are pre-seeded into the database and
selected with a plain query instead of being generated by a model at request time.
"""
import json
import logging
import random
from functools import lru_cache
from pathlib import Path
from typing import Any

from sqlalchemy.orm import Session

from app.models.models import GeneratedQuestion, QuestionFormat, UserAttempt

logger = logging.getLogger(__name__)

BANK_PATH = Path(__file__).resolve().parent.parent / "data" / "question_bank.json"
BANK_SOURCE = "bank"


@lru_cache(maxsize=1)
def load_bank() -> list[dict[str, Any]]:
    """Read the exported question bank from disk (cached for the process lifetime)."""
    if not BANK_PATH.exists():
        logger.warning("Question bank file missing at %s", BANK_PATH)
        return []
    with BANK_PATH.open(encoding="utf-8") as fh:
        return json.load(fh)


def bank_question_count(db: Session, exam_type: str | None = None) -> int:
    query = db.query(GeneratedQuestion)
    if exam_type:
        query = query.filter(GeneratedQuestion.exam_type == exam_type)
    return query.count()


def seed_question_bank(db: Session) -> dict[str, int]:
    """Insert any bank questions that are not already stored. Safe to run repeatedly."""
    items = load_bank()
    if not items:
        return {"available": 0, "inserted": 0, "skipped": 0}

    existing = {
        (row.exam_type, row.topic, row.question_text)
        for row in db.query(
            GeneratedQuestion.exam_type,
            GeneratedQuestion.topic,
            GeneratedQuestion.question_text,
        ).all()
    }

    inserted = 0
    for item in items:
        key = (item["exam_type"], item["topic"], item["question_text"])
        if key in existing:
            continue
        db.add(
            GeneratedQuestion(
                exam_type=item["exam_type"],
                topic=item["topic"],
                difficulty=item["difficulty"],
                question_format=QuestionFormat.multiple_choice,
                question_text=item["question_text"],
                options=item["options"],
                correct_answer=item["correct_answer"],
                explanation=item["explanation"],
                validated=True,
                generation_metadata={"source": BANK_SOURCE, "source_id": item["source_id"]},
            )
        )
        existing.add(key)
        inserted += 1

    db.commit()
    result = {"available": len(items), "inserted": inserted, "skipped": len(items) - inserted}
    logger.info("Question bank seed: %s", result)
    return result


def _seen_question_ids(db: Session, user_id: str, exam_type: str) -> set[str]:
    rows = (
        db.query(UserAttempt.generated_question_id)
        .join(GeneratedQuestion, UserAttempt.generated_question_id == GeneratedQuestion.id)
        .filter(UserAttempt.user_id == user_id, GeneratedQuestion.exam_type == exam_type)
        .all()
    )
    return {row[0] for row in rows if row[0]}


def select_exam_questions(
    db: Session,
    exam_type: str,
    topics: list[str],
    number_of_questions: int,
    user_id: str | None = None,
) -> list[GeneratedQuestion]:
    """Pick a spread of stored questions across the requested topics. No model calls."""
    query = db.query(GeneratedQuestion).filter(GeneratedQuestion.exam_type == exam_type)
    if topics:
        query = query.filter(GeneratedQuestion.topic.in_(topics))
    pool = query.all()
    if not pool:
        return []

    seen = _seen_question_ids(db, user_id, exam_type) if user_id else set()

    by_topic: dict[str, list[GeneratedQuestion]] = {}
    for q in pool:
        by_topic.setdefault(q.topic, []).append(q)

    # Prefer questions the student has not attempted before, then shuffle within each topic.
    for items in by_topic.values():
        random.shuffle(items)
        items.sort(key=lambda q: q.id in seen)

    ordered_topics = [t for t in topics if t in by_topic] or list(by_topic)
    selected: list[GeneratedQuestion] = []
    cursors = {topic: 0 for topic in ordered_topics}

    # Round-robin across topics so the exam covers the curriculum evenly.
    while len(selected) < number_of_questions:
        progressed = False
        for topic in ordered_topics:
            if len(selected) >= number_of_questions:
                break
            idx = cursors[topic]
            items = by_topic[topic]
            if idx < len(items):
                selected.append(items[idx])
                cursors[topic] = idx + 1
                progressed = True
        if not progressed:
            break

    return selected


def main() -> None:
    """CLI entry point: python -m app.services.question_bank"""
    logging.basicConfig(level=logging.INFO)
    from app.db.session import SessionLocal

    db = SessionLocal()
    try:
        print(seed_question_bank(db))
    finally:
        db.close()


if __name__ == "__main__":
    main()
