/**
 * Curriculum Data Structure & Mock Data
 * Defines topics, sections, and progress for each exam
 */

export interface Topic {
  id: string;
  name: string;
  description: string;
  icon: string;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  questionCount: number;
  estimatedHours: number;
  progressPercent: number;
}

export interface Section {
  id: string;
  name: string;
  icon: string;
  description: string;
  topics: Topic[];
  progressPercent: number;
}

export interface CurriculumData {
  examId: string;
  examName: string;
  sections: Section[];
  totalTopics: number;
  totalQuestions: number;
  overallProgressPercent: number;
}

// Mock Curriculum Data for All Exams

export const SAT_CURRICULUM: CurriculumData = {
  examId: 'sat',
  examName: 'SAT',
  sections: [
    {
      id: 'reading-writing',
      name: 'Reading & Writing',
      icon: '📚',
      description: 'Master reading comprehension and writing skills',
      progressPercent: 42,
      topics: [
        {
          id: 'vocabulary',
          name: 'Vocabulary',
          description: 'Master word patterns and context clues',
          icon: '📖',
          difficulty: 'Beginner',
          questionCount: 45,
          estimatedHours: 3,
          progressPercent: 42,
        },
        {
          id: 'grammar',
          name: 'Grammar & Syntax',
          description: 'Learn sentence structure and grammatical rules',
          icon: '✏️',
          difficulty: 'Intermediate',
          questionCount: 60,
          estimatedHours: 4,
          progressPercent: 38,
        },
        {
          id: 'reading-comp',
          name: 'Reading Comprehension',
          description: 'Develop strategies for understanding passages',
          icon: '📖',
          difficulty: 'Intermediate',
          questionCount: 75,
          estimatedHours: 5,
          progressPercent: 35,
        },
        {
          id: 'rhetoric',
          name: 'Rhetoric & Language',
          description: 'Analyze rhetorical devices and author techniques',
          icon: '💬',
          difficulty: 'Advanced',
          questionCount: 40,
          estimatedHours: 3,
          progressPercent: 20,
        },
      ],
    },
    {
      id: 'math',
      name: 'Math',
      icon: '🔢',
      description: 'Build mathematical problem-solving skills',
      progressPercent: 18,
      topics: [
        {
          id: 'algebra',
          name: 'Algebra',
          description: 'Equations, variables, and algebraic expressions',
          icon: 'ⓧ',
          difficulty: 'Intermediate',
          questionCount: 80,
          estimatedHours: 6,
          progressPercent: 12,
        },
        {
          id: 'geometry',
          name: 'Geometry',
          description: 'Shapes, angles, and spatial reasoning',
          icon: '🔺',
          difficulty: 'Advanced',
          questionCount: 50,
          estimatedHours: 4,
          progressPercent: 5,
        },
        {
          id: 'trigonometry',
          name: 'Trigonometry & Functions',
          description: 'Advanced functions and trigonometric ratios',
          icon: '〰️',
          difficulty: 'Advanced',
          questionCount: 40,
          estimatedHours: 4,
          progressPercent: 2,
        },
        {
          id: 'statistics',
          name: 'Statistics & Probability',
          description: 'Data analysis and probability concepts',
          icon: '📊',
          difficulty: 'Intermediate',
          questionCount: 35,
          estimatedHours: 3,
          progressPercent: 18,
        },
      ],
    },
    {
      id: 'essay',
      name: 'Essay (Optional)',
      icon: '✏️',
      description: 'Master essay writing and argumentation',
      progressPercent: 0,
      topics: [
        {
          id: 'essay-structure',
          name: 'Essay Structure',
          description: 'Learn thesis, body paragraphs, and conclusions',
          icon: '📋',
          difficulty: 'Beginner',
          questionCount: 20,
          estimatedHours: 2,
          progressPercent: 0,
        },
        {
          id: 'argumentation',
          name: 'Argumentation & Evidence',
          description: 'Develop compelling arguments with evidence',
          icon: '💭',
          difficulty: 'Intermediate',
          questionCount: 30,
          estimatedHours: 3,
          progressPercent: 0,
        },
      ],
    },
  ],
  totalTopics: 10,
  totalQuestions: 2400,
  overallProgressPercent: 28,
};

export const ACT_CURRICULUM: CurriculumData = {
  examId: 'act',
  examName: 'ACT',
  sections: [
    {
      id: 'english',
      name: 'English',
      icon: '📝',
      description: 'Punctuation, grammar, and writing strategy',
      progressPercent: 35,
      topics: [
        {
          id: 'punctuation',
          name: 'Punctuation',
          description: 'Master comma rules and punctuation marks',
          icon: '.',
          difficulty: 'Beginner',
          questionCount: 50,
          estimatedHours: 3,
          progressPercent: 40,
        },
        {
          id: 'grammar-act',
          name: 'Grammar & Usage',
          description: 'Subject-verb agreement and verb tenses',
          icon: '✏️',
          difficulty: 'Intermediate',
          questionCount: 60,
          estimatedHours: 4,
          progressPercent: 35,
        },
        {
          id: 'rhetorical-skills',
          name: 'Rhetorical Skills',
          description: 'Style, strategy, and organization',
          icon: '💬',
          difficulty: 'Advanced',
          questionCount: 40,
          estimatedHours: 3,
          progressPercent: 25,
        },
      ],
    },
    {
      id: 'mathematics',
      name: 'Mathematics',
      icon: '🔢',
      description: 'Pre-algebra through trigonometry',
      progressPercent: 15,
      topics: [
        {
          id: 'pre-algebra',
          name: 'Pre-Algebra',
          description: 'Basic arithmetic and number concepts',
          icon: '1️⃣',
          difficulty: 'Beginner',
          questionCount: 40,
          estimatedHours: 2,
          progressPercent: 25,
        },
        {
          id: 'elementary-algebra',
          name: 'Elementary Algebra',
          description: 'Basic algebraic concepts and equations',
          icon: 'ⓧ',
          difficulty: 'Intermediate',
          questionCount: 50,
          estimatedHours: 4,
          progressPercent: 10,
        },
        {
          id: 'intermediate-algebra',
          name: 'Intermediate Algebra',
          description: 'Complex equations and functions',
          icon: 'ⓧ',
          difficulty: 'Intermediate',
          questionCount: 45,
          estimatedHours: 4,
          progressPercent: 8,
        },
        {
          id: 'coordinate-geometry',
          name: 'Coordinate Geometry',
          description: 'Graphs, lines, and coordinate planes',
          icon: '📍',
          difficulty: 'Advanced',
          questionCount: 40,
          estimatedHours: 3,
          progressPercent: 5,
        },
        {
          id: 'plane-geometry',
          name: 'Plane Geometry',
          description: 'Shapes, angles, and spatial relationships',
          icon: '🔺',
          difficulty: 'Advanced',
          questionCount: 35,
          estimatedHours: 3,
          progressPercent: 2,
        },
        {
          id: 'trigonometry-act',
          name: 'Trigonometry',
          description: 'Trigonometric ratios and identities',
          icon: '〰️',
          difficulty: 'Advanced',
          questionCount: 25,
          estimatedHours: 2,
          progressPercent: 0,
        },
      ],
    },
    {
      id: 'reading',
      name: 'Reading',
      icon: '📖',
      description: 'Comprehension and analysis skills',
      progressPercent: 28,
      topics: [
        {
          id: 'prose-fiction',
          name: 'Prose Fiction',
          description: 'Literary understanding and analysis',
          icon: '📚',
          difficulty: 'Intermediate',
          questionCount: 40,
          estimatedHours: 3,
          progressPercent: 30,
        },
        {
          id: 'humanities',
          name: 'Humanities',
          description: 'Essays on philosophy, history, and arts',
          icon: '🎭',
          difficulty: 'Advanced',
          questionCount: 40,
          estimatedHours: 3,
          progressPercent: 25,
        },
        {
          id: 'social-science',
          name: 'Social Science',
          description: 'History, political science, sociology',
          icon: '📜',
          difficulty: 'Intermediate',
          questionCount: 40,
          estimatedHours: 3,
          progressPercent: 30,
        },
        {
          id: 'natural-science',
          name: 'Natural Science',
          description: 'Biology, chemistry, physics passages',
          icon: '🔬',
          difficulty: 'Intermediate',
          questionCount: 40,
          estimatedHours: 3,
          progressPercent: 25,
        },
      ],
    },
    {
      id: 'science',
      name: 'Science',
      icon: '🔬',
      description: 'Data analysis and scientific reasoning',
      progressPercent: 12,
      topics: [
        {
          id: 'biology',
          name: 'Biology',
          description: 'Life sciences and cell biology',
          icon: '🧬',
          difficulty: 'Intermediate',
          questionCount: 35,
          estimatedHours: 3,
          progressPercent: 15,
        },
        {
          id: 'chemistry',
          name: 'Chemistry',
          description: 'Chemical equations and reactions',
          icon: '⚗️',
          difficulty: 'Advanced',
          questionCount: 35,
          estimatedHours: 3,
          progressPercent: 8,
        },
        {
          id: 'physics',
          name: 'Physics',
          description: 'Forces, energy, and motion',
          icon: '⚡',
          difficulty: 'Advanced',
          questionCount: 30,
          estimatedHours: 3,
          progressPercent: 5,
        },
        {
          id: 'earth-science',
          name: 'Earth & Space Science',
          description: 'Geology, meteorology, astronomy',
          icon: '🌍',
          difficulty: 'Intermediate',
          questionCount: 30,
          estimatedHours: 2,
          progressPercent: 12,
        },
      ],
    },
  ],
  totalTopics: 17,
  totalQuestions: 2000,
  overallProgressPercent: 22,
};

export const GRE_CURRICULUM: CurriculumData = {
  examId: 'gre',
  examName: 'GRE',
  sections: [
    {
      id: 'verbal-reasoning',
      name: 'Verbal Reasoning',
      icon: '💬',
      description: 'Advanced reading and vocabulary skills',
      progressPercent: 32,
      topics: [
        {
          id: 'text-completion',
          name: 'Text Completion',
          description: 'Fill in blanks with appropriate vocabulary',
          icon: '📝',
          difficulty: 'Intermediate',
          questionCount: 40,
          estimatedHours: 3,
          progressPercent: 35,
        },
        {
          id: 'sentence-equivalence',
          name: 'Sentence Equivalence',
          description: 'Find equivalent sentences and meanings',
          icon: '⚖️',
          difficulty: 'Advanced',
          questionCount: 40,
          estimatedHours: 3,
          progressPercent: 30,
        },
        {
          id: 'reading-comprehension-gre',
          name: 'Reading Comprehension',
          description: 'Complex academic passages and questions',
          icon: '📖',
          difficulty: 'Advanced',
          questionCount: 80,
          estimatedHours: 6,
          progressPercent: 30,
        },
      ],
    },
    {
      id: 'quantitative-reasoning',
      name: 'Quantitative Reasoning',
      icon: '📐',
      description: 'Advanced mathematical problem-solving',
      progressPercent: 18,
      topics: [
        {
          id: 'arithmetic',
          name: 'Arithmetic',
          description: 'Numbers, operations, and calculations',
          icon: '🔢',
          difficulty: 'Beginner',
          questionCount: 50,
          estimatedHours: 3,
          progressPercent: 30,
        },
        {
          id: 'algebra-gre',
          name: 'Algebra',
          description: 'Equations, inequalities, and functions',
          icon: 'ⓧ',
          difficulty: 'Advanced',
          questionCount: 70,
          estimatedHours: 5,
          progressPercent: 12,
        },
        {
          id: 'geometry-gre',
          name: 'Geometry',
          description: 'Shapes, volumes, and coordinate geometry',
          icon: '🔺',
          difficulty: 'Advanced',
          questionCount: 60,
          estimatedHours: 4,
          progressPercent: 10,
        },
        {
          id: 'data-analysis',
          name: 'Data Analysis',
          description: 'Statistics, probability, and graphs',
          icon: '📊',
          difficulty: 'Advanced',
          questionCount: 50,
          estimatedHours: 4,
          progressPercent: 15,
        },
      ],
    },
    {
      id: 'analytical-writing',
      name: 'Analytical Writing',
      icon: '✍️',
      description: 'Essay writing and critical thinking',
      progressPercent: 5,
      topics: [
        {
          id: 'issue-essay',
          name: 'Issue Essay',
          description: 'Respond to an issue with analysis',
          icon: '💭',
          difficulty: 'Advanced',
          questionCount: 40,
          estimatedHours: 4,
          progressPercent: 0,
        },
        {
          id: 'argument-essay',
          name: 'Argument Essay',
          description: 'Analyze and critique an argument',
          icon: '🎯',
          difficulty: 'Advanced',
          questionCount: 40,
          estimatedHours: 4,
          progressPercent: 10,
        },
      ],
    },
  ],
  totalTopics: 9,
  totalQuestions: 1800,
  overallProgressPercent: 20,
};

export const GMAT_CURRICULUM: CurriculumData = {
  examId: 'gmat',
  examName: 'GMAT',
  sections: [
    {
      id: 'analytical-writing-gmat',
      name: 'Analytical Writing',
      icon: '✍️',
      description: 'Essay and critical analysis skills',
      progressPercent: 8,
      topics: [
        {
          id: 'argument-analysis',
          name: 'Argument Analysis',
          description: 'Analyze and critique business arguments',
          icon: '🎯',
          difficulty: 'Advanced',
          questionCount: 20,
          estimatedHours: 2,
          progressPercent: 8,
        },
      ],
    },
    {
      id: 'integrated-reasoning',
      name: 'Integrated Reasoning',
      icon: '🔗',
      description: 'Multi-source reasoning and data analysis',
      progressPercent: 12,
      topics: [
        {
          id: 'table-analysis',
          name: 'Table Analysis',
          description: 'Sort and analyze data in tables',
          icon: '📋',
          difficulty: 'Intermediate',
          questionCount: 30,
          estimatedHours: 2,
          progressPercent: 15,
        },
        {
          id: 'graphics-interpretation',
          name: 'Graphics Interpretation',
          description: 'Interpret charts, graphs, and diagrams',
          icon: '📊',
          difficulty: 'Intermediate',
          questionCount: 30,
          estimatedHours: 2,
          progressPercent: 10,
        },
        {
          id: 'two-part-analysis',
          name: 'Two-Part Analysis',
          description: 'Solve related quantitative problems',
          icon: '⚖️',
          difficulty: 'Advanced',
          questionCount: 25,
          estimatedHours: 2,
          progressPercent: 10,
        },
        {
          id: 'multi-source-reasoning',
          name: 'Multi-Source Reasoning',
          description: 'Extract data from multiple sources',
          icon: '🔗',
          difficulty: 'Advanced',
          questionCount: 25,
          estimatedHours: 2,
          progressPercent: 12,
        },
      ],
    },
    {
      id: 'quantitative',
      name: 'Quantitative (Problem Solving & Data Sufficiency)',
      icon: '🔢',
      description: 'Advanced business mathematics',
      progressPercent: 18,
      topics: [
        {
          id: 'arithmetic-gmat',
          name: 'Arithmetic',
          description: 'Number properties and operations',
          icon: '🔢',
          difficulty: 'Intermediate',
          questionCount: 50,
          estimatedHours: 3,
          progressPercent: 20,
        },
        {
          id: 'algebra-gmat',
          name: 'Algebra',
          description: 'Equations and algebraic reasoning',
          icon: 'ⓧ',
          difficulty: 'Advanced',
          questionCount: 60,
          estimatedHours: 4,
          progressPercent: 15,
        },
        {
          id: 'geometry-gmat',
          name: 'Geometry',
          description: 'Shapes, coordinates, and 3D figures',
          icon: '🔺',
          difficulty: 'Advanced',
          questionCount: 50,
          estimatedHours: 3,
          progressPercent: 15,
        },
        {
          id: 'word-problems',
          name: 'Word Problems',
          description: 'Applied math and business scenarios',
          icon: '💼',
          difficulty: 'Advanced',
          questionCount: 40,
          estimatedHours: 3,
          progressPercent: 20,
        },
      ],
    },
    {
      id: 'verbal',
      name: 'Verbal',
      icon: '💬',
      description: 'Reading comprehension and critical reasoning',
      progressPercent: 22,
      topics: [
        {
          id: 'reading-comp-gmat',
          name: 'Reading Comprehension',
          description: 'Business and academic passages',
          icon: '📖',
          difficulty: 'Advanced',
          questionCount: 70,
          estimatedHours: 5,
          progressPercent: 25,
        },
        {
          id: 'critical-reasoning',
          name: 'Critical Reasoning',
          description: 'Logical arguments and evaluation',
          icon: '🎯',
          difficulty: 'Advanced',
          questionCount: 80,
          estimatedHours: 5,
          progressPercent: 20,
        },
        {
          id: 'sentence-correction',
          name: 'Sentence Correction',
          description: 'Grammar and sentence construction',
          icon: '✏️',
          difficulty: 'Intermediate',
          questionCount: 60,
          estimatedHours: 4,
          progressPercent: 20,
        },
      ],
    },
  ],
  totalTopics: 12,
  totalQuestions: 1600,
  overallProgressPercent: 15,
};

export const SHSAT_CURRICULUM: CurriculumData = {
  examId: 'shsat',
  examName: 'SHSAT',
  sections: [
    {
      id: 'english-language-arts',
      name: 'English Language Arts',
      icon: '📚',
      description: 'Reading and language skills for NYC schools',
      progressPercent: 30,
      topics: [
        {
          id: 'reading-ela',
          name: 'Reading Comprehension',
          description: 'Understanding and analyzing passages',
          icon: '📖',
          difficulty: 'Intermediate',
          questionCount: 50,
          estimatedHours: 3,
          progressPercent: 35,
        },
        {
          id: 'editing-ela',
          name: 'Editing in Context',
          description: 'Grammar and sentence structure',
          icon: '✏️',
          difficulty: 'Intermediate',
          questionCount: 40,
          estimatedHours: 3,
          progressPercent: 25,
        },
      ],
    },
    {
      id: 'mathematics-shsat',
      name: 'Mathematics',
      icon: '🔢',
      description: 'Middle school and pre-algebra mathematics',
      progressPercent: 18,
      topics: [
        {
          id: 'numbers-operations',
          name: 'Numbers & Operations',
          description: 'Basic arithmetic and fractions',
          icon: '🔢',
          difficulty: 'Beginner',
          questionCount: 40,
          estimatedHours: 2,
          progressPercent: 28,
        },
        {
          id: 'algebra-shsat',
          name: 'Algebra',
          description: 'Basic equations and expressions',
          icon: 'ⓧ',
          difficulty: 'Intermediate',
          questionCount: 45,
          estimatedHours: 3,
          progressPercent: 15,
        },
        {
          id: 'geometry-shsat',
          name: 'Geometry',
          description: 'Shapes, angles, and area',
          icon: '🔺',
          difficulty: 'Intermediate',
          questionCount: 40,
          estimatedHours: 3,
          progressPercent: 12,
        },
        {
          id: 'statistics-shsat',
          name: 'Statistics & Probability',
          description: 'Data and probability concepts',
          icon: '📊',
          difficulty: 'Intermediate',
          questionCount: 35,
          estimatedHours: 2,
          progressPercent: 10,
        },
      ],
    },
  ],
  totalTopics: 6,
  totalQuestions: 1200,
  overallProgressPercent: 24,
};

export const REGENTS_CURRICULUM: CurriculumData = {
  examId: 'regents',
  examName: 'Regents',
  sections: [
    {
      id: 'english-regents',
      name: 'English',
      icon: '📚',
      description: 'Comprehensive English skills',
      progressPercent: 25,
      topics: [
        {
          id: 'literature',
          name: 'Literature & Comprehension',
          description: 'Literary analysis and understanding',
          icon: '📖',
          difficulty: 'Intermediate',
          questionCount: 50,
          estimatedHours: 4,
          progressPercent: 28,
        },
        {
          id: 'writing-regents',
          name: 'Writing & Composition',
          description: 'Essay writing and composition',
          icon: '✏️',
          difficulty: 'Intermediate',
          questionCount: 40,
          estimatedHours: 4,
          progressPercent: 22,
        },
      ],
    },
    {
      id: 'mathematics-regents',
      name: 'Mathematics',
      icon: '🔢',
      description: 'Algebra and geometry for NY high schools',
      progressPercent: 20,
      topics: [
        {
          id: 'algebra-i',
          name: 'Algebra I',
          description: 'Equations, functions, and polynomials',
          icon: 'ⓧ',
          difficulty: 'Intermediate',
          questionCount: 90,
          estimatedHours: 6,
          progressPercent: 18,
        },
        {
          id: 'geometry-regents',
          name: 'Geometry',
          description: 'Proofs, angles, and coordinate geometry',
          icon: '🔺',
          difficulty: 'Intermediate',
          questionCount: 80,
          estimatedHours: 6,
          progressPercent: 20,
        },
        {
          id: 'algebra-ii',
          name: 'Algebra II',
          description: 'Advanced functions and sequences',
          icon: 'ⓧ',
          difficulty: 'Advanced',
          questionCount: 90,
          estimatedHours: 6,
          progressPercent: 20,
        },
      ],
    },
    {
      id: 'sciences',
      name: 'Sciences',
      icon: '🔬',
      description: 'Living environment and physical science',
      progressPercent: 15,
      topics: [
        {
          id: 'living-environment',
          name: 'Living Environment',
          description: 'Biology and life sciences',
          icon: '🧬',
          difficulty: 'Intermediate',
          questionCount: 85,
          estimatedHours: 6,
          progressPercent: 18,
        },
        {
          id: 'earth-science-regents',
          name: 'Earth Science',
          description: 'Geology, weather, and astronomy',
          icon: '🌍',
          difficulty: 'Intermediate',
          questionCount: 85,
          estimatedHours: 6,
          progressPercent: 12,
        },
        {
          id: 'physical-science',
          name: 'Physical Science',
          description: 'Physics and chemistry fundamentals',
          icon: '⚡',
          difficulty: 'Advanced',
          questionCount: 80,
          estimatedHours: 6,
          progressPercent: 12,
        },
      ],
    },
    {
      id: 'social-studies',
      name: 'Social Studies',
      icon: '📜',
      description: 'Global history and US history',
      progressPercent: 22,
      topics: [
        {
          id: 'global-history',
          name: 'Global History & Geography',
          description: 'World history and geography',
          icon: '🌏',
          difficulty: 'Intermediate',
          questionCount: 100,
          estimatedHours: 8,
          progressPercent: 20,
        },
        {
          id: 'us-history',
          name: 'US History & Government',
          description: 'American history and civics',
          icon: '🗽',
          difficulty: 'Intermediate',
          questionCount: 100,
          estimatedHours: 8,
          progressPercent: 24,
        },
      ],
    },
  ],
  totalTopics: 9,
  totalQuestions: 1400,
  overallProgressPercent: 20,
};

// Helper function to get curriculum by exam ID
export function getCurriculumByExamId(examId: string): CurriculumData {
  const curriculumMap: Record<string, CurriculumData> = {
    sat: SAT_CURRICULUM,
    act: ACT_CURRICULUM,
    gre: GRE_CURRICULUM,
    gmat: GMAT_CURRICULUM,
    shsat: SHSAT_CURRICULUM,
    regents: REGENTS_CURRICULUM,
  };

  return curriculumMap[examId] || SAT_CURRICULUM;
}
